service: stratostruct-lambda
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  profile: default
  region: eu-west-2
  environment:
  MONGO_URI: ${env:MONGO_URI}
  SECRET: ${env:SECRET}
  MAPBOX_API_KEY: ${env:MAPBOX_API_KEY}


functions:
  app:
    handler: handler.handler
    events:
      - http:
          path: /
          method: any
      - http:
          path: /{proxy+}
          method: any
